### ISSUE TITLE
Creation of new projects fails

### ISSUE THREAD

**Issue by fsiddi** [oenvoyage/brender#4]
After filling the form, an entry on the table appears (with the right paths) but the title of the project does not. When a new job is created, in the dropdown list the project appears as an empty entry. Job submission does not work.

**Comment by oenvoyage** [comment]
fixed

**Comment by ghost** [comment]
Hmm .. seems like it's not fixed, because I have this error too!

**Comment by fsiddi** [comment]
Are you using the latest version I guess? Maybe your issue is related to paths, check out the other issue (where I suggest you to try absolute paths).
